const firebaseConfig = {
    apiKey: "AIzaSyDVO9IzpWNpLwH9iLew_33-yAjwF0J-cZY",
    authDomain: "esmo-data.firebaseapp.com",
    projectId: "esmo-data",
    storageBucket: "esmo-data.firebasestorage.app",
    messagingSenderId: "153190804837",
    appId: "1:153190804837:web:7799fceb93a7e9bde7058c",
    measurementId: "G-DGCY76DCWH"
};

// Initialize Firebase (Assuming compat SDK is loaded in HTML)
if (typeof firebase !== 'undefined') {
    firebase.initializeApp(firebaseConfig);
    window.db = firebase.firestore();
} else {
    console.error("Firebase SDK is not loaded.");
}

window.characters = [
    "Automata", "Blight", "Brewer", "Brute", "Charmer", "Chronos", "Cinder", "Corsair",
    "Councilor", "Dagger", "Dervish", "Dredge", "Driller", "Drowner", "Empress", "Engineer",
    "Equinox", "Exile", "Fencer", "Gambler", "Gauntlet", "Gladiator", "Gloom", "Grappler",
    "Harvester", "Havoc", "Hellblade", "Illusionist", "Inquisitor", "Jester", "Juggler",
    "Kunai", "Lancer", "Leviathan", "Lupine", "Maestro", "Mantra", "Monk", "Monolith",
    "Nomad", "Oculus", "Paladin", "Paragon", "Pembroke", "Pixie", "Predator", "Protector",
    "Purifier", "Reaper", "Riptide", "Seeker", "Sentinel", "Sludge", "Smith", "Sniper",
    "Spark", "Stellar", "Sting", "Strider", "Symbiote", "Torrent", "Treant", "Umbra",
    "Ursine", "Usurper", "Vermin", "Vixen", "Volt", "Warper", "Widow", "Witch", "Zephyr"
];

window.characterRoles = {
    "Automata": ["MID"],
    "Blight": ["BOT"],
    "Brewer": ["JUNGLE"],
    "Brute": ["TOP"],
    "Charmer": ["SUPPORT"],
    "Chronos": ["SUPPORT"],
    "Cinder": ["BOT"],
    "Corsair": ["BOT"],
    "Councilor": ["MID"],
    "Dagger": ["MID"],
    "Dervish": ["TOP"],
    "Dredge": ["SUPPORT"],
    "Driller": ["TOP"],
    "Drowner": ["SUPPORT"],
    "Empress": ["MID", "JUNGLE"],
    "Engineer": ["MID"],
    "Equinox": ["JUNGLE"],
    "Exile": ["TOP"],
    "Fencer": ["TOP"],
    "Gambler": ["MID"],
    "Gauntlet": ["JUNGLE"],
    "Gladiator": ["TOP", "JUNGLE"],
    "Gloom": ["MID"],
    "Grappler": ["SUPPORT"],
    "Harvester": ["SUPPORT"],
    "Havoc": ["BOT"],
    "Hellblade": ["TOP"],
    "Illusionist": ["MID"],
    "Inquisitor": ["BOT"],
    "Jester": ["JUNGLE"],
    "Juggler": ["BOT"],
    "Kunai": ["MID"],
    "Lancer": ["SUPPORT"],
    "Leviathan": ["JUNGLE"],
    "Lupine": ["JUNGLE"],
    "Maestro": ["BOT"],
    "Mantra": ["SUPPORT"],
    "Monk": ["JUNGLE"],
    "Monolith": ["TOP"],
    "Nomad": ["MID"],
    "Oculus": ["MID"],
    "Paladin": ["TOP"],
    "Paragon": ["TOP"],
    "Pembroke": ["MID", "BOT"],
    "Pixie": ["SUPPORT"],
    "Predator": ["JUNGLE"],
    "Protector": ["SUPPORT"],
    "Purifier": ["BOT"],
    "Reaper": ["JUNGLE"],
    "Riptide": ["MID"],
    "Seeker": ["BOT"],
    "Sentinel": ["TOP", "SUPPORT"],
    "Sludge": ["BOT"],
    "Smith": ["TOP"],
    "Sniper": ["BOT"],
    "Spark": ["BOT"],
    "Stellar": ["MID"],
    "Sting": ["JUNGLE"],
    "Strider": ["TOP"],
    "Symbiote": ["BOT"],
    "Torrent": ["BOT"],
    "Treant": ["TOP", "SUPPORT"],
    "Umbra": ["MID"],
    "Ursine": ["TOP", "JUNGLE"],
    "Usurper": ["MID", "JUNGLE"],
    "Vermin": ["BOT"],
    "Vixen": ["MID"],
    "Volt": ["TOP"],
    "Warper": ["MID"],
    "Widow": ["JUNGLE"],
    "Witch": ["MID", "SUPPORT"],
    "Zephyr": ["SUPPORT"]
};
